config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#index'

  devise_for :users

  resources :hotels, only: [:index, :show] do
    resources :images
    resources :affiliates
  end
  resources :countries, only: [:index, :show]
  resources :cities, only: [:index, :show]

  namespace :provider do
    resources :hotels do
      post 'add_articles'
      post 'remove_articles'
      patch :image_arrangement, on: :member
    end
  end

  namespace :admin do
    resources :cities, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :countries, only: [:index, :create, :new, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < User
  default_scope { where(role: 'admin') }
end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base
  belongs_to :hotel
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
  has_many :hotels

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :provider
  belongs_to :city
  has_many :affiliates
  has_many :images, -> { order(:position) }, as: :imageable
  accepts_nested_attributes_for :images, allow_destroy: true
  validates_presence_of :name, :city_id, :description, :address
  attr_accessor :article
  include AASM

  aasm do
    state :pending, initial: true
    state :approved
    state :declined
    
    event :approve, after: :approval_email do
      transitions from: [:pending, :declined], to: :approved
    end

    event :decline, after: :declination_email do
      transitions from: [:pending, :approved], to: :declined
    end
  end

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :name,
      [:name, :city_id],
      [:name, :city_id, :id]
    ]
  end

  def approval_email
  end

  def declination_email
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  include ImageUploader[:image]

  belongs_to :imageable, polymorphic: true
  # validates_presence_of :image_data

end

app/models/image_uploader.rb
require "image_processing/mini_magick"

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :activerecord
  plugin :determine_mime_type
  plugin :logging, logger: Rails.logger
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :versions, names: [:original, :thumb, :small, :medium]

  Attacher.validate do
    validate_max_size 3.megabytes, message: 'is too large (max is 3 MB)'
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  end

  def process(io, context)
    case context[:phase]
    when :store
      medium = resize_to_limit!(io.download, 800, 600)
      small = resize_to_limit!(io.download, 500, 500)
      thumb = resize_to_limit!(io.download, 100, 100)
      { original: io, medium: medium, small: small, thumb: thumb }
    end
  end
end

app/models/provider.rb
class Provider < User
  default_scope { where(role: 'provider') }

  has_many :hotels

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend Enumerize
  enumerize :role, in: [:user, :admin, :provider], predicates: true, default: :user

  extend FriendlyId
  friendly_id :firstname, use: [:slugged, :finders]
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :firstname,
      [:firstname, :lastname],
      [:firstname, :lastname, :id]
    ]
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :country_id, :status, :slug, :description)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @related_articles = @hotel.articles.map { |a| OpenGraph.new(a)} 
    gon.affiliates = @hotel.affiliates
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
	  :user
	end

	def resource
	  @resource ||= User.new
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-warning"
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def store_location
    session[:return_to] = request.original_url
  end

  def deny_access
    redirect_to new_user_session_path
  end
 
  def anyone_signed_in?
    !current_user.nil?
  end
 
  private
 
  def clear_stored_location
    session[:return_to] = nil
  end
end

app/views/layouts/_meta.html.slim
= metamagic title: 'Tripcanvas hotels listing', viewport:'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', description: 'Tripcanvas hotels listings site', keywords: 'hotel listings, reviews for hotels', og: { title: 'Tripcanvas Hotel Listings', site_name: 'Tripcanvas Hotel Listings', type: "website", image: "", url: "#{request.original_url}", description: 'Tripcanvas hotels listings site'}

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    = growlyflash_static_notices
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
    = favicon_link_tag 'mts-favicon.png'
    = Gon::Base.render_data
    = render 'layouts/meta'

  body
    .wrapper
      = render "users/sessions/login_modal" 
      = render "users/registrations/signup_modal" 
      - if controller.controller_name == 'hotels' && controller.action_name == 'show'
        = render 'shared/navbar_hotel'
      - else
        = render 'shared/navbar'
      = yield

app/views/pages/index.html.slim
#fullscreen_post_bg style="background-image: url(#{image_url('villabhuvana.jpg')}); top center no-repeat"
  .overlay
.container
  .header
    .header-overlay
    .tagline-box
      h1#logo Tripcanvas
      h3.subheading Your Hotel Insider
      .row.row-space-top-8
        .col-xs-1.col-md-4
        .col-xs-10.col-md-4
          .space-top-md-5
            - if user_signed_in? && current_user.provider?
              = button_to 'My Hotels', provider_hotels_path, method: :get, class: "btn btn-info btn-block"
              p
              = button_to 'All Hotels', hotels_path, method: :get, class: "btn btn-warning btn-block"
            - elsif user_signed_in? && current_user.user?
              = button_to 'View Hotels', hotels_path, method: :get, class: "btn btn-warning btn-block"
            - else
              = button_to 'Login', '#', remote: true, data: { toggle: 'modal', target: '.modal--login' }, class: "btn btn-success btn-block"
        .col-xs-1.col-md-4

app/views/shared/_article.html.slim
/ .col-xs-12.col-sm-4.col-md-6.col-lg-4  
/   .card-container
/     .card
/       = link_to a.url, target: "_blank", class: "link-reset"
/         .photo
/           img.fill.img-responsive src="#{image_url(a.images.first)}"
/         .details
/           h3.h5.text-truncate.article-name title=a.title
/             strong #{a.title}
/           .media.clearfix style=("margin:0;")
/             - if a.description
/               .text-muted
/                 = strip_tags(a.description.html_safe.truncate(75))
.card-segment-body.list-unstyled-card 
  .inlinerec-source-card 
    = link_to a.url, target: "_blank"
      .inlinerec-thumb-card style="background-image: url('#{image_url(a.images.first)}');"
      .inlinerec-content-card
        h4 #{a.title}
        p.source-card
          span.favicon
            i.fa.fa-globe
          |TripCanvas › #{h.city.country.name} › #{h.city.name}

app/views/shared/_footer.html.slim
footer.footer-basic-centered
 p.footer-company-motto
 p 
   = link_to 'https://www.tripcanvas.co', class: 'navbar-brand' do
     = image_tag('tripcanvas_logo_color_320x130.png')
 p.footer-links
  / a href="#" Home
  / |·
  / a href="#" Blog
  / |·
  / a href="#" Pricing
  / |·
  / a href="#" About
  / |·
  / a href="#" Faq
  / |·
  / a href="#" Contact 
 p.footer-company-name
   / | TripCanvas &copy; 2016

app/views/shared/_navbar.html.slim
//for landing page only
.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag('tripcanvas_logo_color_320x130.png')
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.visible-xs
        - unless user_signed_in?
        - if user_signed_in?
          li = link_to t('nav.logout'), destroy_user_session_path, method: :delete
          li = link_to 'My Hotel', provider_hotels_path
          li = link_to 'New Hotel', new_provider_hotel_path
        - else
          li = link_to t('nav.signup'), '#', data: { toggle: 'modal', target: '.modal--sign_up' }
          li = link_to t('nav.login'), '#', data: { toggle: 'modal', target: '.modal--login' }
      .pull-right.hidden-xs style=('display:inline-block;')
        ul.nav.navbar-nav
          - if user_signed_in?
            li 
              = link_to "#", class:"dropdown dropdown-toggle link-contrast dove", data: {toggle:"dropdown"}, aria: { haspopup:"true", expanded:"false" }
                = image_tag('https://placehold.it/30x30', class: 'img-circle img-circle-white avatar avatar-original', style: 'width: 30px; height: 30px;')
                |  #{current_user.email}
                i.fa.fa-caret-down
              ul.dropdown-menu.bullet.pull-right
                li = link_to 'My Hotel', provider_hotels_path
                li = link_to 'Create Hotel', new_provider_hotel_path
                li = link_to 'Logout', destroy_user_session_path, method: :delete
          - else
            li = link_to 'Sign Up', '#', data: { toggle: 'modal', target: '.modal--sign_up' }, class: "dove"
            li = link_to 'Login', '#', data: { toggle: 'modal', target: '.modal--login' }, class: "dove"

app/views/shared/_navbar_hotel.html.slim
//for landing page only
.navbar.navbar-default aria-hidden="true"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'https://www.tripcanvas.co', class: 'navbar-brand' do
        = image_tag('tripcanvas_logo_color_320x130.png')
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.visible-xs
        li = link_to 'Photos', '#js-carousel_service', class: "dove"
        li = link_to 'About this hotel', '#hotel_summary', class: "dove"
        li = link_to 'Article highlights', '#related_articles', class: "dove"
        li = link_to 'Map', '#hotel_map', class: "dove"
      .pull-left.hidden-xs style=('display:inline-block;')
        ul.nav.navbar-nav
          li = link_to 'Photos', '#js-carousel_service', class: "dove"
          li = link_to 'About this hotel', '#hotel_summary', class: "dove"
          li = link_to 'Article highlights', '#related_articles', class: "dove"
          li = link_to 'Map', '#hotel_map', class: "dove"
.subnav.section-titles.hide-md data-sticky="true" data-transition-at="#hotel_summary" aria-hidden="true"
  .page-container-responsive
    ul.subnav-list
      li = link_to 'Photos', '#js-carousel_service', class: "subnav-item", id: "photoButton", aria: { selected: 'false' }
      li = link_to 'About this hotel', '#hotel_summary', class: "subnav-item", id: "summaryButton", aria: { selected: 'false' }
      li = link_to 'Article highlights', '#related_articles', class: "subnav-item", id: "articleButton", aria: { selected: 'false' }
      li = link_to 'Map', '#hotel_map', class: "subnav-item", id: "mapButton", aria: { selected: 'false' }
      
javascript:
  $(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
  });

app/views/shared/_navbar_hotel.slim
//for landing page only
.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'https://www.tripcanvas.co', class: 'navbar-brand' do
        = image_tag('tripcanvas_logo_color_320x130.png')
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.visible-xs
        li = link_to 'Photos', '#js-carousel_service', class: "dove"
        li = link_to 'About this hotel', '#hotel_summary', class: "dove"
        li = link_to 'Article highlights', '#related_articles', class: "dove"
        li = link_to 'Map', '#hotel_map', class: "dove"
      .pull-left.hidden-xs style=('display:inline-block;')
        ul.nav.navbar-nav
          li = link_to 'Photos', '#js-carousel_service', class: "dove"
          li = link_to 'About this hotel', '#hotel_summary', class: "dove"
          li = link_to 'Article highlights', '#related_articles', class: "dove"
          li = link_to 'Map', '#hotel_map', class: "dove"
.subnav.section-titles.hide-md data-sticky="true" data-transition-at="#hotel_summary" aria-hidden="true"
  .page-container-responsive
    ul.subnav-list
      li = link_to 'Photos', '#js-carousel_service', class: "subnav-item"
      li = link_to 'About this hotel', '#hotel_summary', class: "subnav-item"
      li = link_to 'Map', '#hotel_map', class: "subnav-item"
      li = link_to 'Article highlights', '#related_articles', class: "subnav-item"
      
javascript:
  $(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
  });