config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#index'

  devise_for :users

  resources :hotels, only: [:index, :show] do
    resources :images
    resources :affiliates
  end
  resources :countries, only: [:index, :show]
  resources :cities, only: [:index, :show]

  namespace :provider do
    resources :hotels do
      post 'add_articles'
      post 'remove_articles'
      patch :image_arrangement, on: :member
    end
  end

  namespace :admin do
    resources :cities, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :countries, only: [:index, :create, :new, :edit, :update, :destroy]
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :provider
  belongs_to :city
  has_many :affiliates
  has_many :images, -> { order(:position) }, as: :imageable
  accepts_nested_attributes_for :images, allow_destroy: true
  validates_presence_of :name, :city_id, :description, :address
  attr_accessor :article
  include AASM

  aasm do
    state :pending, initial: true
    state :approved
    state :declined
    
    event :approve, after: :approval_email do
      transitions from: [:pending, :declined], to: :approved
    end

    event :decline, after: :declination_email do
      transitions from: [:pending, :approved], to: :declined
    end
  end

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :name,
      [:name, :city_id],
      [:name, :city_id, :id]
    ]
  end

  def approval_email
  end

  def declination_email
  end
end

app/models/provider.rb
class Provider < User
  default_scope { where(role: 'provider') }

  has_many :hotels

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @related_articles = @hotel.articles.map { |a| OpenGraph.new(a)} 
    gon.affiliates = @hotel.affiliates
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end
end

app/controllers/provider/affiliates_controller.rb
class Provider::AffiliatesController < ApplicationController
  before_action :set_hotel, only: [:create]
  before_action :set_image, only: [:destroy, :update]

  def index
    @affiliates = @hotel.affiliates
  end

  def create
    image = @hotel.affiliates.create(affiliate_params)
    redirect_to :back, notice: 'Affiliate created'
    # render partial: "photo", locals: {image: image, idx: @resource.images.count}
  end

  def update
    @hotel.update(affiliate_params)
    redirect_to root_path
  end

  def destroy
    redirect_to :back, notice: 'Affiliate was successfully removed!' if @affiliate.destroy
  end

  private
  
  def set_affiliate
    @affiliate = Affiliate.find(params[:id])
  end

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def affiliate_params
    params.require(:affiliate).permit(:affiliate_id, :affiliate_label, :code, :remove_affiliate)
  end
end

app/controllers/provider/base_controller.rb
class Provider::BaseController < ApplicationController  
  before_action :authenticate_provider!
  before_action :set_resource

  private

  def set_resource
    @provider = Provider.find(current_user.id)
  end
end

app/controllers/provider/hotels_controller.rb
class Provider::HotelsController < Provider::BaseController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:edit]  

  def index
    @hotels = @provider.hotels
  end

  def new
    @hotel = @provider.hotels.new
    @cities = City.all
    @countries = Country.all
  end

  # GET /hotels/1/edit
  def edit
    @cities = City.all
    @countries = Country.all
    @image_arrangement_form = ImageArrangementForm.new(hotel_id: @hotel.id)
  end

  def show
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = @provider.hotels.new(hotel_params)
    
    respond_to do |format|
      if @hotel.save
        format.html { redirect_to edit_provider_hotel_path(id: @hotel.id), notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { render :edit, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to provider_hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_articles
    @hotel = @provider.hotels.find(params[:hotel_id])
    @hotel.articles.push(params[:hotel][:article])
    respond_to do |format|
      if @hotel.save
        format.html { redirect_to edit_provider_hotel_path(id: params[:hotel_id]), notice: 'added articles' }
      else
        format.html { render :edit, notice: 'fail to add articles' }
      end
    end
  end

  def remove_articles
    @hotel = @provider.hotels.find(params[:hotel_id])
    @hotel.articles.delete(params[:hotel][:article])
    respond_to do |format|
      if @hotel.save
        format.html { redirect_to edit_provider_hotel_path(id: params[:hotel_id]), notice: 'removed articles' }
      else
        format.html { render :edit, notice: 'fail to add articles' }
      end
    end
  end

  def image_arrangement
    @image_arrangement_form = ImageArrangementForm.new(image_arrangement_params)

    if @image_arrangement_form.save
      redirect_to :back
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = @provider.hotels.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :city_id, :aasm_state, :slug, :description, :address, :email, :website, :phone_no, :article, :articles)
    end
    
    def set_category
      @category = case params[:c]
        when 'photos' then 'photos'
        when 'affiliates' then 'affiliates'
      end
    end
    
    def image_arrangement_params
      params.require(:image_arrangement_form).permit(:hotel_id, image_attributes: [:id, :position, :caption])
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/provider/hotels_helper.rb
module Provider::HotelsHelper
end

app/views/provider/hotels/_affiliates.html.slim
.row
  - if @hotel.affiliates.present?
    - @hotel.affiliates.each do |a|
      .col-md-6
        .panel.row-space-4
          .panel-header
            = image_tag('bookdotcom/booking_logo_retina.png', style: 'width: 130px; height: 30px;') if a.affiliate_label == 'bookingdotcom'
            = image_tag('agoda/agoda-logo.png', style: 'width: 80px; height: 30px;') if a.affiliate_label == 'agoda'
          .panel-body.highlight-panel-header
            .row
              .col-xs-12
                ul.list-unstyled
                  li 
                    strong Affiliate_id: 
                    |#{a.affiliate_id}
                  li 
                    strong Hotel_id: 
                    |#{a.code}
                  li
                    strong Hotel_url: 
                    | #{a.url}
          .panel-footer style='padding: 10px;'
            = button_to 'Delete This', hotel_affiliate_path(hotel_id: @hotel.id, id: a.id), data: {:confirm => 'Are you sure to remove this affiliate?'}, method: :delete, class: 'btn btn-danger'
p
= link_to 'New Affiliate', '#', data: { toggle: 'modal', target: '.modal--new_affiliate' }, class: 'btn btn-success'
p
= render 'new_affiliate_modal'

app/views/provider/hotels/_edit_articles_modal.html.slim
.modal--edit_articles.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss='modal' &times;
      .modal-body
        p.lead.text-center
          | Related articles
        - if @hotel.articles.present?
          - @hotel.articles.each do |ar|
            = form_for @hotel, url: provider_hotel_remove_articles_path(hotel_id: @hotel.id), method: :post do |c|
              .row.row-condensed.space-4
                .col-sm-12
                  .input-group
                    = c.text_field :article, value: ar, class: 'form-control', required: true
                    span.input-group-btn
                      button.btn.btn-danger
                        | Delete
        - else
          .text-center
            | Please add an article below
      .modal-footer
        = form_for @hotel, url: provider_hotel_add_articles_path(hotel_id: @hotel.id), method: :post do |c|
          .row.row-condensed.space-4
            .col-sm-12
              .input-group
                = c.text_field :article, placeholder: 'enter single article url', class: 'form-control', required: true
                span.input-group-btn
                  button.btn.btn-primary
                    | Add

app/views/provider/hotels/_edit_hotel_form.html.slim
= tinymce_assets
= simple_form_for @hotel, url: provider_hotel_path(id: @hotel.id), method: :patch do |f|
  - if @hotel.errors.any?
    #error_explanation
      h2 = "#{pluralize(@hotel.errors.count, "error")} prohibited this hotel from being saved:"
      ul
        - @hotel.errors.full_messages.each do |message|
          li = message
  .row.row-condensed.space-4
    .col-sm-6
      .field
        = f.input :name, required: true
    .col-sm-6
      .field
        = f.association :city, as: :select, required: true, prompt: "Select city"
  .row.row-condensed.space-4
    .col-sm-12
      .field
        = f.input :description, as: :text, input_html: {class: "tinymce", rows: 15}
  .row.row-condensed.space-4
    .col-sm-6 
      .field
        = f.input :address, as: :url, required: true
    .col-sm-6
      .field
        = f.input :phone_no, as: :tel, placeholder: '+1 (234) 567 890'
  .row.row-condensed.space-4
    .col-sm-6 
      .field
        = f.input :website, placeholder: 'http://'
    .col-sm-6 
      .field
        = f.input :email, as: :email
  .row.row-condensed.space-2
    .col-sm-12
      .actions = f.button :submit, class: 'btn btn-success btn-block'
= tinymce :alternate

app/views/provider/hotels/_form.html.slim
= simple_form_for @hotel, url: path do |f|
  - if @hotel.errors.any?
    #error_explanation
      h2 = "#{pluralize(@hotel.errors.count, "error")} prohibited this hotel from being saved:"
      ul
        - @hotel.errors.full_messages.each do |message|
          li = message
  .row.row-condensed.space-4
    .col-sm-6
      .field
        = f.input :name, required: true
    .col-sm-6
      .field
        = f.association :city, as: :select, required: true, prompt: "Select city"
  .row.row-condensed.space-4
    .col-sm-12
      .field
        = f.input :description, as: :ckeditor, input_html: { :ckeditor => {:toolbar => 'simple'} }
  .row.row-condensed.space-4
    .col-sm-6 
      .field
        = f.input :address, as: :url, required: true
    .col-sm-6
      .field
        = f.input :phone_no, as: :tel, placeholder: '+1 (234) 567 890'
  .row.row-condensed.space-4
    .col-sm-6 
      .field
        = f.input :website, placeholder: 'http://'
    .col-sm-6 
      .field
        = f.input :email, as: :email
  .row.row-condensed.space-2
    .col-sm-12
      .actions = f.button :submit, class: 'btn btn-success btn-block'

app/views/provider/hotels/_new_affiliate_modal.html.slim
.modal--new_affiliate.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      = simple_form_for @hotel.affiliates.new, url: hotel_affiliates_path(@hotel), method: :post do |i|
        .modal-header
          button.close data-dismiss='modal' &times;
        .modal-body
          p.lead.text-center
            | New Affiliate
          span.help-block
          .form-group
            = i.input :affiliate_label, label: 'Affiliate Provider', as: :radio_buttons, collection: ['bookingdotcom','agoda'], prompt: "Select partner"      
          span.help-block
          .form-group
            = i.input :affiliate_id, as: :integer, label: 'Affiliate id'
          span.help-block
          .form-group
            = i.input :code, as: :integer, label: 'Hotel code'
          span.help-block
          .form-group
            = i.input :url, as: :string, label: 'Hotel url'
        .modal-footer
          .form-group
            = i.button :submit

app/views/provider/hotels/_new_photo_modal.html.slim
.modal--new_photo.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      = simple_form_for @hotel.images.new, url: hotel_images_path(@hotel), method: :post do |i|
        .modal-header
          button.close data-dismiss='modal' &times;
        .modal-body
          p.lead.text-center
            | Add Photo
          span.help-block
          .form-group
            = i.input :image, as: :file
          .form-group
            = i.input :caption
        .modal-footer
          .form-group
            = i.button :submit

app/views/provider/hotels/_photos.html.slim
.row
  .col-12
    = form_for @image_arrangement_form, url: image_arrangement_provider_hotel_path, method: :patch, remote: true do |f|
      = f.hidden_field :hotel_id, value: @hotel.id
      ul.sortable__list.js-sortable
        = f.fields_for :image do |img|
          li.sortable__item
            .delete-photo-btn.overlay-btn.js-delete-photo-btn
              i = link_to '', hotel_image_path(id: img.object.id, hotel_id: @hotel.id), data: {:confirm => 'Are you sure to remove this image?'}, method: :delete, class: 'fa fa-trash'
            = image_tag img.object.image_url(:small), class: "img-responsive"
            = img.hidden_field :position
            = img.text_area :caption
p
= link_to 'New Photo', '#', data: { toggle: 'modal', target: '.modal--new_photo' }, class: 'btn btn-success'
p
= render 'new_photo_modal'

coffee:
  TC.sortable.servicePhoto.init()

app/views/provider/hotels/edit.html.slim
.container
  - if params[:c].present?
    h3 Editing #{@hotel.name}'s #{@category}
    hr
    = render @category
  - else
    h3 Editing #{@hotel.name}
    hr
    == render 'form', path: provider_hotel_path
    .row
      .col-md-4
        = link_to 'Edit Related Articles', '#', data: { toggle: 'modal', target: '.modal--edit_articles' }, class: 'btn btn-info btn-block'
      .col-md-4
        = button_to 'Edit Photos', edit_provider_hotel_path(@hotel), method: :get, class: 'btn btn-warning btn-block', params: { c: 'photos' }
      .col-md-4
        = button_to 'Edit Affiliates', edit_provider_hotel_path(@hotel), method: :get, class: 'btn btn-primary btn-block', params: { c: 'affiliates' }
  = link_to 'Show', @hotel
  '|
  = link_to 'Back', provider_hotels_path
= render 'edit_articles_modal'

app/views/provider/hotels/index.html.slim
= javascript_include_tag 'https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js'
.container
  h1 My hotels

  table#hotels.table.table-striped.table-bordered cellspacing="0" width="100%"
    thead
      tr
        th Name
        th City
        th Address
        th Phone No
        th
        th
    tbody
      - @hotels.each do |hotel|
        tr
          td = link_to hotel.name, hotel
          td = City.find(hotel.city_id).name
          td = hotel.address
          td = hotel.phone_no
          td = button_to 'Edit', edit_provider_hotel_path(hotel), method: :get, class: 'btn btn-success btn-block'
          td = button_to 'Delete Hotel', provider_hotel_path(hotel), data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger btn-block'

javascript:
  $('#hotels').DataTable({
    scrollY:        "500px",
    scrollX:        true,
    scrollCollapse: true,
    paging:         false,
    columnDefs: [
        { width: '30%', targets: 2 }
    ],
    fixedColumns: true  
  });

app/views/provider/hotels/new.html.slim
.container
  h1 New hotel
  == render 'form', path: provider_hotels_path

  = link_to 'Back', provider_hotels_path