config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#index'

  devise_for :users

  resources :hotels, only: [:index, :show] do
    resources :images
    resources :affiliates
  end
  resources :countries, only: [:index, :show]
  resources :cities, only: [:index, :show]

  namespace :provider do
    resources :hotels do
      post 'add_articles'
      post 'remove_articles'
      patch :image_arrangement, on: :member
    end
  end

  namespace :admin do
    resources :cities, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :countries, only: [:index, :create, :new, :edit, :update, :destroy]
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
  has_many :hotels

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :country_id, :status, :slug, :description)
    end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.slim
= form_for @country do |f|
  - if @country.errors.any?
    #error_explanation
      h2 = "#{pluralize(@country.errors.count, "error")} prohibited this country from being saved:"
      ul
        - @country.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :country_id
    = f.number_field :country_id
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/countries/edit.html.slim
h1 Editing country

== render 'form'

= link_to 'Show', @country
'|
= link_to 'Back', countries_path

app/views/countries/index.html.slim
h1 Listing countries

table
  thead
    tr
      th Name
      th Country
      th Status
      th Slug
      th Description
      th
      th
      th

  tbody
    - @countries.each do |country|
      tr
        td = country.name
        td = country.country_id
        td = country.status
        td = country.slug
        td = country.description
        td = link_to 'Show', country
        td = link_to 'Edit', edit_country_path(country)
        td = link_to 'Destroy', country, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Country', new_country_path

app/views/countries/new.html.slim
h1 New country

== render 'form'

= link_to 'Back', countries_path

app/views/countries/show.html.slim
p#notice = notice

p
  strong Name:
  = @country.name
p
  strong Country:
  = @country.country_id
p
  strong Status:
  = @country.status
p
  strong Slug:
  = @country.slug
p
  strong Description:
  = @country.description

= link_to 'Edit', edit_country_path(@country)
'|
= link_to 'Back', countries_path