config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#index'

  devise_for :users

  resources :hotels, only: [:index, :show] do
    resources :images
    resources :affiliates
  end
  resources :countries, only: [:index, :show]
  resources :cities, only: [:index, :show]

  namespace :provider do
    resources :hotels do
      post 'add_articles'
      post 'remove_articles'
      patch :image_arrangement, on: :member
    end
  end

  namespace :admin do
    resources :cities, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :countries, only: [:index, :create, :new, :edit, :update, :destroy]
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < ApplicationController
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :country_id, :status, :slug, :description)
    end
end

app/helpers/admin/cities_helper.rb
module Admin::CitiesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.slim
= form_for @city do |f|
  - if @city.errors.any?
    #error_explanation
      h2 = "#{pluralize(@city.errors.count, "error")} prohibited this city from being saved:"
      ul
        - @city.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :country_id
    = f.number_field :country_id
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/cities/edit.html.slim
h1 Editing city

== render 'form'

= link_to 'Show', @city
'|
= link_to 'Back', cities_path

app/views/cities/index.html.slim
h1 Listing cities

table
  thead
    tr
      th Name
      th Country
      th Status
      th Slug
      th Description
      th
      th
      th

  tbody
    - @cities.each do |city|
      tr
        td = city.name
        td = city.country_id
        td = city.status
        td = city.slug
        td = city.description
        td = link_to 'Show', city
        td = link_to 'Edit', edit_city_path(city)
        td = link_to 'Destroy', city, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New City', new_city_path

app/views/cities/new.html.slim
h1 New city

== render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.slim
p#notice = notice

p
  strong Name:
  = @city.name
p
  strong Country:
  = @city.country_id
p
  strong Status:
  = @city.status
p
  strong Slug:
  = @city.slug
p
  strong Description:
  = @city.description

= link_to 'Edit', edit_city_path(@city)
'|
= link_to 'Back', cities_path